apiVersion: v1
kind: Service
metadata:
  name: composition-service
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
  selector:
    app: composition
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: composition-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: composition
        version: 0.0.1
    spec:
      containers:
        - name: composition
          image: composition:0.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "80"
            - name: APP_URL_POSTS
              value: http://posts-service:80/posts
            - name: APP_URL_COMMENTS
              value: http://comments-service:80/comments
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-keys
                  key: public
                  optional: false
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: jwt-keys
                  key: issuer
                  optional: false
            - name: JWT_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: jwt-keys
                  key: audience
                  optional: false
  selector:
    matchLabels:
      app: composition
