apiVersion: v1
kind: Service
metadata:
  name: comments-service
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
  selector:
    app: comments
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: comments
        version: 0.0.1
    spec:
      containers:
        - name: comments
          image: comments:0.0.1
          imagePullPolicy: Never
          ports:
            # pura documentação (caráter informativo), igual o EXPOSE do Dockerfile
            - containerPort: 80
              protocol: TCP
          env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "80"
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-keys
                  key: public
                  optional: false
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: jwt-keys
                  key: issuer
                  optional: false
            - name: JWT_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: jwt-keys
                  key: audience
                  optional: false
  selector:
    matchLabels:
      app: comments
