apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: auth
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
        version: 0.0.1
    spec:
      containers:
        - name: auth
          image: auth:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3000"
            - name: JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-keys
                  key: private
                  optional: false
  selector:
    matchLabels:
      app: auth
